"""sidequest.protocol — WebSocket protocol types for the SideQuest game engine.

Re-exports all public symbols from the protocol sub-modules so callers can
import directly from sidequest.protocol without knowing the internal layout.

Port of sidequest-protocol (Rust crate) to Python via pydantic.
"""

from __future__ import annotations

# Dice payloads (story 34 — ported 2026-04-24)
from sidequest.protocol.dice import (
    DiceRequestPayload,
    DiceResultPayload,
    DiceThrowPayload,
    DieGroupResult,
    DieSides,
    DieSpec,
    OpposedRollResult,
    RollOutcome,
    ThrowParams,
)

# Local DM decomposer output contract (Group B)
from sidequest.protocol.dispatch import (
    CrossAction,
    DispatchPackage,
    LethalityVerdict,
    LethalityVerdictKind,
    NarratorDirective,
    NarratorDirectiveKind,
    PerceptionFidelity,
    PlayerDispatch,
    Referent,
    Reversibility,
    SubsystemDispatch,
    VisibilityTag,
)

# Foundation types
from sidequest.protocol.enums import MessageType, NarratorVerbosity, NarratorVocabulary

# Fate Core payloads (ADR-144 F1d)
from sidequest.protocol.fate import FateActionPayload

# Phase 1 payload classes
from sidequest.protocol.messages import (
    ActionQueueMessage,
    ActionQueuePayload,
    ChapterMarkerMessage,
    ChapterMarkerPayload,
    CharacterCreationMessage,
    CharacterCreationPayload,
    CharacterIncapacitatedMessage,
    CharacterIncapacitatedPayload,
    DiceRequestMessage,
    DiceResultMessage,
    DiceThrowMessage,
    ErrorMessage,
    ErrorPayload,
    FateActionMessage,
    GameMessage,
    LocationDescriptionMessage,
    LocationOverlayChangedMessage,
    NarrationEndMessage,
    NarrationEndPayload,
    NarrationMessage,
    NarrationPayload,
    PartyStatusMessage,
    PartyStatusPayload,
    PlayerActionMessage,
    PlayerActionPayload,
    QuestsMessage,
    RelationshipsMessage,
    SessionEventMessage,
    SessionEventPayload,
    TacticalGridMessage,
    ThinkingMessage,
    ThinkingPayload,
    TurnStatusEntry,
    TurnStatusMessage,
    TurnStatusPayload,
)

# Nested model types
from sidequest.protocol.models import (
    CellularParams,
    CharacterSheetDetails,
    CharacterState,
    CreationChoice,
    DerivedRoomData,
    DispositionBeatPayload,
    EncounterLocationOverlay,
    FactCategory,
    Footnote,
    InitialState,
    InitiativeEntry,
    InventoryItem,
    InventoryPayload,
    ItemGained,
    LocationDescriptionOverlaySummary,
    LocationDescriptionPayload,
    LocationEntity,
    LocationEntityBinding,
    LocationOverlayChangedPayload,
    PartyMember,
    QuestAnchorEntry,
    QuestLogEntry,
    QuestsPayload,
    RelationshipClaimPayload,
    RelationshipEntry,
    RelationshipsPayload,
    RolledStat,
    StateDelta,
    TacticalGridPayload,
    TokenPayload,
)
from sidequest.protocol.provenance import (
    ContributionKind,
    MergeStep,
    Provenance,
    Span,
    Tier,
)
from sidequest.protocol.sanitize import sanitize_player_text
from sidequest.protocol.types import NonBlankString, Stat

__all__ = [
    # Dice payloads (story 34)
    "DiceRequestPayload",
    "DiceResultPayload",
    "DiceThrowPayload",
    "DieGroupResult",
    "DieSides",
    "DieSpec",
    "OpposedRollResult",
    "RollOutcome",
    "ThrowParams",
    "DiceRequestMessage",
    "DiceResultMessage",
    "DiceThrowMessage",
    # Local DM decomposer (Group B)
    "CrossAction",
    "DispatchPackage",
    "LethalityVerdict",
    "LethalityVerdictKind",
    "NarratorDirective",
    "NarratorDirectiveKind",
    "PerceptionFidelity",
    "PlayerDispatch",
    "Referent",
    "Reversibility",
    "SubsystemDispatch",
    "VisibilityTag",
    # Foundation
    "MessageType",
    "NarratorVerbosity",
    "NarratorVocabulary",
    # Fate Core payloads (ADR-144 F1d)
    "FateActionPayload",
    "ContributionKind",
    "MergeStep",
    "Provenance",
    "Span",
    "Tier",
    "sanitize_player_text",
    "NonBlankString",
    "Stat",
    # Nested models
    "CellularParams",
    "CharacterSheetDetails",
    "CharacterState",
    "CreationChoice",
    "DerivedRoomData",
    "EncounterLocationOverlay",
    "FactCategory",
    "Footnote",
    "InitialState",
    "InitiativeEntry",
    "InventoryItem",
    "InventoryPayload",
    "ItemGained",
    "LocationDescriptionOverlaySummary",
    "LocationDescriptionPayload",
    "LocationEntity",
    "LocationEntityBinding",
    "LocationOverlayChangedPayload",
    "PartyMember",
    "DispositionBeatPayload",
    "QuestLogEntry",
    "QuestAnchorEntry",
    "QuestsPayload",
    "RelationshipClaimPayload",
    "RelationshipEntry",
    "RelationshipsPayload",
    "RolledStat",
    "StateDelta",
    "TacticalGridPayload",
    "TokenPayload",
    # Phase 1 payloads + messages
    "ActionQueueMessage",
    "ActionQueuePayload",
    "CharacterCreationMessage",
    "CharacterCreationPayload",
    "CharacterIncapacitatedMessage",
    "CharacterIncapacitatedPayload",
    "ChapterMarkerMessage",
    "ChapterMarkerPayload",
    "ErrorMessage",
    "ErrorPayload",
    "FateActionMessage",
    "GameMessage",
    "LocationDescriptionMessage",
    "LocationOverlayChangedMessage",
    "NarrationEndMessage",
    "NarrationEndPayload",
    "NarrationMessage",
    "NarrationPayload",
    "PartyStatusMessage",
    "PartyStatusPayload",
    "QuestsMessage",
    "PlayerActionMessage",
    "PlayerActionPayload",
    "RelationshipsMessage",
    "SessionEventMessage",
    "SessionEventPayload",
    "TacticalGridMessage",
    "ThinkingMessage",
    "ThinkingPayload",
    "TurnStatusEntry",
    "TurnStatusMessage",
    "TurnStatusPayload",
]
